### ISSUE TITLE
Add support for expo sdk 48+

### ISSUE THREAD

**Issue by roni-castro** [itsramiel/with-shopify-react-native-performance#1]
The plugin currently does not support expo version 48+

![Screenshot 2024-11-13 at 12 09 42](https://github.com/user-attachments/assets/3349199d-3d39-476c-adb0-d4874c26658b)

* It would need to update this [peerDependency](https://github.com/itsramiel/with-shopify-react-native-performance/blob/8ea41c004f44a9c62c8715ee16567cc2d8c46ab7/package.json#L46) to be   `">=47"`

* This does not work on Expo 52, for example, because expo MainApplication now is a Kotlin file, so there's no longer [public void onCreate](https://github.com/itsramiel/with-shopify-react-native-performance/blob/main/src/withPerformance.android.ts#L8), so. It actually needs to update the script itself and also some depdencies.

![Screenshot 2024-11-13 at 12 27 08](https://github.com/user-attachments/assets/16e82060-f067-44d1-b8f5-de28f2da3c6e)

**Comment by itsramiel** [comment]
Hi @roni-castro 

I am no longer maintaining this, so I would not want to update it and library users assume I still am.

Feel free to fork and update it!

**Comment by roni-castro** [comment]
> Hi @roni-castro
> 
> I am no longer maintaining this, so I would not want to update it and library users assume I still am.
> 
> Feel free to fork and update it!

No problem @itsramiel. I'm trying creating a new one using this [code](https://github.com/Shopify/react-native-performance/pull/145/files) and yours as a reference, as there's being some changes in expo config plugin and also in native code

**Comment by itsramiel** [comment]
Awesome to hear you are working on it!

Glad the code here is of help to you.
Best of luck!
